name: whisper_server
description: A sample command-line application.
version: 0.0.0
repository: https://github.com/azkadev/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  lints: ^2.0.0
  packagex: ^0.0.13
  test: ^1.21.0
dependencies:
  alfred: ^1.1.0+1
  galaxeus_lib: ^0.0.55
  isar: ^3.0.5
  path: ^1.8.3
  whisper_dart: ^0.0.11
