name: Build libs

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get -y install cmake

      - name: Build libs
        run: |
          cd native_lib/
          echo "Building for Linux"
          echo "=================="
          git submodule update --init --recursive
          bash tools/android_build.sh arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: build_android_arm64/
