name: Build libs

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: sudo apt-get -y install cmake

      - name: Build libs
        run: bash tool/android_build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: libs
          path: build_android_arm64/wisper/
